"""Config loader for the make_mascot pipeline.

Schema source of truth: docs/phase_0_v2/fsd/make_mascot.md §3.2.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path
from typing import Any

import yaml


REQUIRED_TOP_LEVEL = {
    "character_name",
    "bible_path",
    "output_dir",
    "final_atlas_dir",
    "seed",
    "base_model",
    "lora_training",
    "sprite_layers",
    "canvas",
}

REQUIRED_LAYERS = ("expression", "mouth", "tail", "ears")


@dataclasses.dataclass(frozen=True)
class LoraTraining:
    rank: int
    steps: int
    learning_rate: float
    batch_size: int
    augmentation_count: int


@dataclasses.dataclass(frozen=True)
class Canvas:
    sprite_size: int
    atlas_columns: int
    alpha_threshold: float


@dataclasses.dataclass(frozen=True)
class Config:
    character_name: str
    display_name_kr: str
    bible_path: Path
    output_dir: Path
    final_atlas_dir: Path
    seed: int
    base_model: str
    lora_training: LoraTraining
    sprite_layers: dict[str, dict[str, Any]]
    canvas: Canvas
    raw: dict[str, Any]

    def stage_dir(self, stage_name: str) -> Path:
        return self.output_dir / stage_name

    def all_sprite_states(self) -> list[tuple[str, str]]:
        """Return [(layer, state), ...] in canonical order, 24 entries for Daramzzi."""
        out: list[tuple[str, str]] = []
        for layer in REQUIRED_LAYERS:
            for state in self.sprite_layers[layer]["states"]:
                out.append((layer, state))
        return out


def load_config(path: str | Path) -> Config:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Config not found: {path}\n"
            "Run `python pipeline.py init` to generate the FSD §3.2 default."
        )
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    missing = REQUIRED_TOP_LEVEL - set(data)
    if missing:
        raise ValueError(f"Config missing required keys: {sorted(missing)}")

    layers_data = data["sprite_layers"]
    for layer in REQUIRED_LAYERS:
        if layer not in layers_data:
            raise ValueError(f"sprite_layers missing required layer: {layer}")
        if "states" not in layers_data[layer]:
            raise ValueError(f"sprite_layers.{layer} missing 'states'")

    cfg_dir = path.parent.resolve()

    def _resolve(p: str) -> Path:
        pp = Path(p)
        return pp if pp.is_absolute() else (cfg_dir / pp).resolve()

    lora = LoraTraining(
        rank=int(data["lora_training"]["rank"]),
        steps=int(data["lora_training"]["steps"]),
        learning_rate=float(data["lora_training"]["learning_rate"]),
        batch_size=int(data["lora_training"]["batch_size"]),
        augmentation_count=int(data["lora_training"]["augmentation_count"]),
    )
    canvas = Canvas(
        sprite_size=int(data["canvas"]["sprite_size"]),
        atlas_columns=int(data["canvas"]["atlas_columns"]),
        alpha_threshold=float(data["canvas"]["alpha_threshold"]),
    )

    return Config(
        character_name=str(data["character_name"]),
        display_name_kr=str(data.get("display_name_kr", data["character_name"])),
        bible_path=_resolve(data["bible_path"]),
        output_dir=_resolve(data["output_dir"]),
        final_atlas_dir=_resolve(data["final_atlas_dir"]),
        seed=int(data["seed"]),
        base_model=str(data["base_model"]),
        lora_training=lora,
        sprite_layers=layers_data,
        canvas=canvas,
        raw=data,
    )


DEFAULT_CONFIG_YAML = """\
# Daramzzi make_mascot config — FSD docs/phase_0_v2/fsd/make_mascot.md §3.2
# Generated by `pipeline.py init`. Edit before running stages if needed.
character_name: daramzzi
display_name_kr: 다람찌
bible_path: ../../../docs/characters/daramzzi.md
output_dir: ./work
final_atlas_dir: ./atlas
seed: 20260513
base_model: Qwen/Qwen-Image
lora_training:
  rank: 32
  steps: 1500
  learning_rate: 1.0e-4
  batch_size: 1
  augmentation_count: 8
sprite_layers:
  expression:
    count: 10
    states:
      - neutral
      - cheek_stuff
      - panic
      - pleading
      - victory
      - sleepy
      - confused
      - sneaky
      - laughing
      - embarrassed
  mouth:
    count: 6
    states: [closed, aa, ih, ou, ee, oh]
  tail:
    count: 5
    states: [relaxed, alert, puffed, curled, wagging]
  ears:
    count: 3
    states: [up, flat, perked]
canvas:
  sprite_size: 1024
  atlas_columns: 6
  alpha_threshold: 0.1
"""
